"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function RegistrationPage() {
  const router=useRouter(); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const values=new FormData(event.currentTarget); try { const response=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyName:values.get("companyName"),name:values.get("name"),email:values.get("email"),password:values.get("password")})}); const payload=await response.json(); if(!response.ok) throw new Error(payload.error ?? "Inscription impossible"); const login=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:values.get("email"),password:values.get("password")})}); if(!login.ok) throw new Error("Compte créé. Connectez-vous pour continuer."); router.replace("/clients"); router.refresh(); } catch(registrationError) { setError(registrationError instanceof Error ? registrationError.message : "Inscription impossible"); } finally { setLoading(false); } }
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><a className="brand" href="/"><span className="brand-mark">D</span><span>Distrib<span>Flow</span></span></a><div><h1>Créez votre entreprise</h1><p>Commencez par votre compte propriétaire.</p></div>{error && <div className="form-error" role="alert">{error}</div>}<label>Nom de l’entreprise<input required name="companyName" minLength={2} /></label><label>Votre nom<input required name="name" minLength={2} autoComplete="name" /></label><label>Adresse e-mail<input required name="email" type="email" autoComplete="email" /></label><label>Mot de passe<input required name="password" type="password" minLength={12} autoComplete="new-password" /><small>12 caractères minimum.</small></label><button className="primary" disabled={loading}>{loading ? "Création…" : "Créer mon compte"}</button><p className="auth-link">Déjà inscrit ? <a href="/connexion">Se connecter</a></p></form></main>;
}
