import Link from "next/link";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { ArrowRight, Boxes, ClipboardList, Package, Truck, Users } from "lucide-react";
import { ProtectedPage } from "@/components/protected-page";
import { getSessionDetails } from "@/lib/services/auth";
import { canonicalRole } from "@/lib/tenant";

export default async function EmployeeWorkspacePage() { const session = await getSessionDetails((await cookies()).get("distribflow_session")?.value); if (!session) redirect("/connexion"); const role = canonicalRole(session.role); const modules = role === "SALES" ? [{ href: "/clients", title: "Clients", description: "Consulter et suivre votre portefeuille.", icon: Users }, { href: "/commandes", title: "Commandes", description: "Créer et suivre les commandes autorisées.", icon: ClipboardList }] : role === "WAREHOUSE" ? [{ href: "/stock", title: "Stock", description: "Consulter les niveaux et opérations autorisées.", icon: Boxes }, { href: "/preparation", title: "Préparation", description: "Ouvrir la file de picking.", icon: Package }] : role === "DRIVER" ? [] : [{ href: "/dashboard", title: "Tableau de bord", description: "Consulter les indicateurs accessibles.", icon: Boxes }, { href: "/commandes", title: "Commandes", description: "Consulter les commandes de l’entreprise.", icon: ClipboardList }]; return <ProtectedPage><main className="content"><div className="page-heading"><div><p className="eyebrow">Espace employé</p><h1>Bonjour {session.userName}</h1><p>Retrouvez uniquement les modules correspondant à votre rôle.</p></div></div>{role === "DRIVER" ? <section className="panel empty-state workspace-card"><Truck size={30} color="var(--blue-600)" /><strong>Module livraisons bientôt disponible</strong><p>Le périmètre livraison sera ouvert dans une prochaine phase.</p></section> : <section className="workspace-grid">{modules.map((module) => <Link className="panel workspace-module" href={module.href} key={module.href}><div className="metric-icon"><module.icon size={19} /></div><h2>{module.title}</h2><p>{module.description}</p><span>Ouvrir <ArrowRight size={15} /></span></Link>)}</section>}</main></ProtectedPage>; }
