"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { ImagePlus, Trash2, Upload } from "lucide-react";

type Branding = { name: string; logoUrl: string | null; logoSize: number | null };
export default function CompanyBrandingClient({ canEdit }: { canEdit: boolean }) {
  const [data, setData] = useState<Branding | null>(null); const [name, setName] = useState(""); const [preview, setPreview] = useState(""); const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { fetch("/api/tenant/branding", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload); setName(payload.name); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Impossible de charger la marque")).finally(() => setLoading(false)); }, []);
  const selectFile = (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0] ?? null; setFile(selected); setError(""); if (selected) setPreview(URL.createObjectURL(selected)); };
  const saveName = async () => { setPending(true); setError(""); setNotice(""); try { const response = await fetch("/api/tenant/branding", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData((current) => current ? { ...current, name: payload.name } : current); setNotice("Nom de l’entreprise mis à jour."); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Enregistrement impossible"); } finally { setPending(false); } };
  const saveLogo = async () => { if (!file) return; setPending(true); setError(""); setNotice(""); try { const body = new FormData(); body.set("logo", file); const response = await fetch("/api/tenant/branding", { method: "POST", body }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData((current) => current ? { ...current, logoUrl: payload.logoObjectKey ? "/api/tenant/branding/logo" : null, logoSize: payload.logoSize } : current); setFile(null); setPreview(""); setNotice("Logo enregistré."); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : "Logo impossible à enregistrer"); } finally { setPending(false); } };
  const removeLogo = async () => { if (!window.confirm("Supprimer le logo de l’entreprise ?")) return; setPending(true); setError(""); try { const response = await fetch("/api/tenant/branding", { method: "DELETE" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData((current) => current ? { ...current, logoUrl: null, logoSize: null } : current); setNotice("Logo supprimé."); } catch (removeError) { setError(removeError instanceof Error ? removeError.message : "Suppression impossible"); } finally { setPending(false); } };
  if (loading) return <section className="panel empty-state">Chargement de la marque…</section>;
  return <section className="branding-layout">{error && <div className="form-error" role="alert">{error}</div>}{notice && <div className="toast" role="status">{notice}</div>}<section className="panel branding-preview"><div className="branding-logo">{preview || data?.logoUrl ? <img src={preview || data?.logoUrl || ""} alt="Aperçu du logo" /> : <span>{data?.name.slice(0, 2).toUpperCase()}</span>}</div><div><p className="eyebrow">Aperçu</p><h2>{data?.name}</h2><p>Le logo apparaît dans la barre latérale et les documents imprimés.</p></div></section><section className="panel branding-form"><div className="section-heading"><div><h2>Identité de l’entreprise</h2><p>Un nom clair et une marque sobre pour vos équipes.</p></div><ImagePlus size={20} /></div>{canEdit ? <><label>Nom affiché<input value={name} onChange={(event) => setName(event.target.value)} maxLength={120} /></label><div className="branding-actions"><button className="primary" disabled={pending} onClick={() => void saveName()}>Enregistrer le nom</button></div><label className="upload-zone" htmlFor="company-logo"><Upload size={18} /><strong>Choisir un logo</strong><span>PNG, JPEG ou WebP · 2 Mo maximum</span><input id="company-logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={selectFile} /></label>{file && <div className="branding-actions"><button className="primary" disabled={pending} onClick={() => void saveLogo()}>Téléverser ce logo</button><button className="outline" type="button" onClick={() => { setFile(null); setPreview(""); }}>Annuler</button></div>}{data?.logoUrl && !file && <button className="destructive button-sm" disabled={pending} onClick={() => void removeLogo()}><Trash2 size={15} />Supprimer le logo</button>}</> : <div className="empty-state"><strong>Accès en lecture seule</strong><p>Seuls le propriétaire et les administrateurs peuvent modifier la marque.</p></div>}</section></section>;
}
