"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Boxes, ChevronDown, LayoutDashboard, LogOut, Menu, Package, Settings, Users, Warehouse, ClipboardList, X } from "lucide-react";
import { createContext, useContext, useState } from "react";

const links = [{ href: "/dashboard", label: "Tableau de bord", icon: LayoutDashboard }, { href: "/clients", label: "Clients", icon: Users }, { href: "/commandes", label: "Commandes", icon: ClipboardList, roles: ["PLATFORM_ADMIN", "OWNER", "SALES_AGENT", "WAREHOUSE_MANAGER", "ACCOUNTANT", "VIEWER"] }, { href: "/preparation", label: "Préparation", icon: ClipboardList, roles: ["PLATFORM_ADMIN", "OWNER", "SALES_AGENT", "WAREHOUSE_MANAGER", "ACCOUNTANT", "VIEWER"] }, { href: "/catalogue/produits", label: "Produits", icon: Package }, { href: "/catalogue/categories", label: "Catégories", icon: Boxes }, { href: "/catalogue/unites", label: "Unités", icon: Boxes }, { href: "/entrepots", label: "Entrepôts", icon: Warehouse }, { href: "/stock", label: "Stock", icon: ClipboardList }, { href: "/stock/mouvements", label: "Mouvements", icon: ClipboardList }, { href: "/stock/alertes", label: "Alertes", icon: Boxes }];
export const RoleContext = createContext("VIEWER");
export function useRole() { return useContext(RoleContext); }
export function AppShell({ children, session }: { children: React.ReactNode; session: { userName: string; tenantName: string; role: string } }) { const path=usePathname(),router=useRouter(),[open,setOpen]=useState(false),[menu,setMenu]=useState(false); const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"});router.replace("/connexion");router.refresh()}; const visibleLinks=links.filter((link)=>!link.roles||link.roles.includes(session.role)||session.role==="PLATFORM_ADMIN"||session.role==="OWNER"); return <RoleContext.Provider value={session.role}><div className="shell app-shell"><aside className={open?"sidebar open":"sidebar"}><Link className="brand" href="/dashboard"><span className="brand-mark">D</span><span>Distrib<span>Flow</span></span></Link><div className="tenant"><div className="avatar teal">{session.tenantName.slice(0,2).toUpperCase()}</div><div><strong>{session.tenantName}</strong><small>Entreprise</small></div></div><nav>{visibleLinks.map(({href,label,icon:Icon})=><Link onClick={()=>setOpen(false)} className={path===href?"nav-active":""} key={href} href={href}><Icon size={18}/>{label}</Link>)}</nav><div className="sidebar-bottom"><Link href="/parametres/profil"><Settings size={18}/>Paramètres</Link><div className="user-menu"><button onClick={()=>setMenu(!menu)} className="user"><div className="avatar purple">{session.userName.slice(0,2).toUpperCase()}</div><div><strong>{session.userName}</strong><small>{session.role.replaceAll("_"," ")}</small></div><ChevronDown size={16}/></button>{menu&&<button className="logout" onClick={logout}><LogOut size={16}/>Se déconnecter</button>}</div></div></aside><section className="workspace"><header><button className="mobile-menu" aria-label="Ouvrir le menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><strong>{session.tenantName}</strong><small className="header-subtitle">{session.userName}</small></div></header>{children}</section></div></RoleContext.Provider> }
