"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Bell, ClipboardList, LogOut, Menu, MessageCircle, UserRound, X } from "lucide-react";
import { useEffect, useState } from "react";
import { RoleContext } from "@/components/app-shell";
const labels: Record<string, string> = { SALES: "Commercial", WAREHOUSE: "Entrepôt", DRIVER: "Livreur", READ_ONLY: "Lecture seule" };
export function WorkerShell({ children, session }: { children: React.ReactNode; session: { userName: string; tenantName: string; tenantLogoUrl?: string; role: string } }) {
  const path = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false); const [unread, setUnread] = useState(0);
  useEffect(() => { fetch("/api/notifications?unread=1", { cache: "no-store" }).then((response) => response.ok ? response.json() : null).then((payload) => setUnread(payload?.unreadCount ?? 0)).catch(() => undefined); }, [path]);
  const role = session.role === "SALES_AGENT" ? "SALES" : session.role === "WAREHOUSE_MANAGER" ? "WAREHOUSE" : session.role === "VIEWER" ? "READ_ONLY" : session.role;
  const links = [{ href: "/travailleur", label: "Accueil", icon: UserRound }, ...(role === "WAREHOUSE" ? [{ href: "/travailleur/preparation", label: "Préparation", icon: ClipboardList }] : role === "SALES" ? [{ href: "/travailleur/commandes", label: "Commandes", icon: ClipboardList }] : role === "DRIVER" ? [{ href: "/travailleur/livraisons", label: "Livraisons", icon: ClipboardList }] : []), { href: "/travailleur/messages", label: "Messages", icon: MessageCircle }, { href: "/travailleur/notifications", label: "Notifications", icon: Bell }];
  const logout = async () => { await fetch("/api/auth/logout", { method: "POST" }); router.replace("/travailleur/connexion"); router.refresh(); };
  return <RoleContext.Provider value={role}><div className="worker-shell"><header className="worker-header"><button className="mobile-menu" aria-label={open ? "Fermer le menu" : "Ouvrir le menu"} onClick={() => setOpen(!open)}>{open ? <X size={21} /> : <Menu size={21} />}</button><Link className="brand" href="/travailleur"><span className="brand-mark">D</span><span>Distrib<span>Flow</span></span></Link><div className="worker-company">{session.tenantLogoUrl ? <img src={session.tenantLogoUrl} alt="" /> : <span>{session.tenantName.slice(0, 2).toUpperCase()}</span>}<div><strong>{session.tenantName}</strong><small>{labels[role] ?? role}</small></div></div><div className="worker-user"><strong>{session.userName}</strong><button className="icon-button" aria-label="Se déconnecter" onClick={() => void logout()}><LogOut size={17} /></button></div></header><div className="worker-body"><aside className={open ? "worker-nav open" : "worker-nav"}><nav aria-label="Navigation employé">{links.map(({ href, label, icon: Icon }) => <Link className={path === href || (href !== "/travailleur" && path.startsWith(`${href}/`)) ? "active" : ""} href={href} key={href} onClick={() => setOpen(false)}><Icon size={18} /><span>{label}</span>{label === "Notifications" && unread > 0 && <b>{unread}</b>}</Link>)}</nav><Link href="/travailleur/profil" onClick={() => setOpen(false)}><UserRound size={18} />Mon profil</Link></aside><main className="worker-main">{children}</main></div></div></RoleContext.Provider>;
}
