import { z } from "zod";
import { MovementType, Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { assertTenant, can, type Role } from "@/lib/tenant";

const optionalText = z.string().trim().min(1).max(500).optional().transform((value) => value || undefined);
const customerAddressSchema = z.object({ label: z.string().trim().min(1).max(80), address: z.string().trim().min(4).max(500), isDefault: z.boolean().default(false) });
export const customerSchema=z.object({name:z.string().trim().min(2).max(160),phone:optionalText,whatsapp:optionalText,taxIdentifier:optionalText,creditLimit:z.coerce.number().finite().min(0).max(10_000_000).default(0),paymentTermsDays:z.coerce.number().int().min(0).max(365).default(0),notes:z.string().trim().max(2_000).optional().transform((value) => value || undefined),addresses:z.array(customerAddressSchema).max(20).default([])}).superRefine((data, issue) => { if (data.addresses.filter((address) => address.isDefault).length > 1) issue.addIssue({ code: z.ZodIssueCode.custom, path: ["addresses"], message: "Une seule adresse peut être définie par défaut" }); });
export const productSchema=z.object({sku:z.string().trim().min(2).max(80),barcode:optionalText,name:z.string().trim().min(2).max(200),description:z.string().trim().max(2000).optional(),unit:z.string().trim().min(1).max(30),sellingPrice:z.coerce.number().finite().min(0),purchasePrice:z.coerce.number().finite().min(0).default(0),taxRate:z.coerce.number().finite().min(0).max(100).default(19),minimumStock:z.coerce.number().finite().min(0).default(0),categoryId:z.string().min(1).optional()});
const ctx=(context:{tenantId?:string;role:Role},permission:string)=>{if(!can(context.role,permission))throw new Error("Action non autorisée");return assertTenant(context.tenantId)};
const text=z.string().trim().min(1);
const warehouseSchema=z.object({name:text.min(2)});
const categorySchema=z.object({name:text.min(2)});
const unitSchema=z.object({name:text.min(2),symbol:text.max(12)});
const normalized=(value?:string)=>value?.replace(/[^+\d]/g,"")||undefined;
const normalizedTaxIdentifier=(value?: string)=>value?.replace(/\s+/g, "").toUpperCase() || undefined;
const customerInclude = { addresses: { orderBy: [{ isDefault: "desc" as const }, { label: "asc" as const }] } };
type CustomerContext = {tenantId?: string; role: Role};
function customerData(data: z.infer<typeof customerSchema>) { return { ...data, phone: normalized(data.phone), whatsapp: normalized(data.whatsapp), taxIdentifier: normalizedTaxIdentifier(data.taxIdentifier), creditLimit: new Prisma.Decimal(data.creditLimit), addresses: { create: data.addresses.map((address) => ({ ...address })) } }; }
function duplicateCustomerError(error: unknown): never { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new Error("Un client avec ce téléphone ou identifiant fiscal existe déjà"); throw error; }
export async function createCustomer(input:unknown,context:CustomerContext){const tenantId=ctx(context,"customers:write"),data=customerSchema.parse(input);try{return await prisma.customer.create({data:{...customerData(data),tenantId},include:customerInclude});}catch(error){return duplicateCustomerError(error)}}
export async function listCustomers(context:CustomerContext, options: { query?: string; page?: number; pageSize?: number; active?: boolean; sort?: "name" | "createdAt" } = {}) { const tenantId=ctx(context,"customers:read"); const query=options.query?.trim() ?? ""; const page=Math.max(1, options.page ?? 1); const pageSize=Math.min(100, Math.max(1, options.pageSize ?? 25)); const where={tenantId, ...(options.active === undefined ? {} : {active: options.active}), ...(query ? {OR:[{name:{contains:query,mode:"insensitive" as const}},{phone:{contains:normalized(query),mode:"insensitive" as const}},{whatsapp:{contains:normalized(query),mode:"insensitive" as const}},{taxIdentifier:{contains:normalizedTaxIdentifier(query),mode:"insensitive" as const}}]} : {})}; const [items,total]=await prisma.$transaction([prisma.customer.findMany({where,include:customerInclude,take:pageSize,skip:(page-1)*pageSize,orderBy:options.sort === "createdAt" ? {createdAt:"desc"} : {name:"asc"}}),prisma.customer.count({where})]); return {items, pagination:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))}}; }
export async function getCustomer(id:string,context:CustomerContext) { const tenantId=ctx(context,"customers:read"); const customer=await prisma.customer.findFirst({where:{id,tenantId},include:customerInclude}); if(!customer) throw new Error("Client introuvable"); return customer; }
export async function updateCustomer(id:string,input:unknown,context:CustomerContext) { const tenantId=ctx(context,"customers:write"), data=customerSchema.parse(input); const existing=await prisma.customer.findFirst({where:{id,tenantId},select:{id:true}}); if(!existing) throw new Error("Client introuvable"); try { return await prisma.$transaction(async (transaction) => { await transaction.customerAddress.deleteMany({where:{customerId:id}}); return transaction.customer.update({where:{id},data:{...customerData(data)},include:customerInclude}); }); } catch(error) { return duplicateCustomerError(error); } }
export async function setCustomerActive(id:string,active:boolean,context:CustomerContext) { const tenantId=ctx(context,"customers:write"); const result=await prisma.customer.updateMany({where:{id,tenantId},data:{active}}); if(!result.count) throw new Error("Client introuvable"); return getCustomer(id,context); }
function productData(data:z.infer<typeof productSchema>){return {...data,sku:data.sku.toUpperCase(),barcode:data.barcode?.replace(/\s/g,""),sellingPrice:new Prisma.Decimal(data.sellingPrice),purchasePrice:new Prisma.Decimal(data.purchasePrice),taxRate:new Prisma.Decimal(data.taxRate),minimumStock:new Prisma.Decimal(data.minimumStock)}}
function duplicateProductError(error:unknown):never{if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")throw new Error("Un produit avec cette référence existe déjà");throw error}
export async function createProduct(input:unknown,context:CustomerContext){const tenantId=ctx(context,"stock:write"),data=productSchema.parse(input);if(data.categoryId&&!await prisma.productCategory.findFirst({where:{id:data.categoryId,tenantId,active:true}}))throw new Error("Catégorie introuvable");try{return await prisma.product.create({data:{...productData(data),tenantId},include:{category:true}})}catch(error){return duplicateProductError(error)}}
export async function listProducts(context:CustomerContext,options:{query?:string;page?:number;pageSize?:number;active?:boolean}={}){const tenantId=ctx(context,"stock:read"),query=options.query?.trim()??"",page=Math.max(1,options.page??1),pageSize=Math.min(100,Math.max(1,options.pageSize??25));const where={tenantId,...(options.active===undefined?{}:{active:options.active}),...(query?{OR:[{sku:{contains:query,mode:"insensitive" as const}},{barcode:{contains:query,mode:"insensitive" as const}},{name:{contains:query,mode:"insensitive" as const}}]}:{})};const [items,total]=await prisma.$transaction([prisma.product.findMany({where,include:{category:true},orderBy:{name:"asc"},take:pageSize,skip:(page-1)*pageSize}),prisma.product.count({where})]);return{items,pagination:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))}}}
export async function updateProduct(id:string,input:unknown,context:CustomerContext){const tenantId=ctx(context,"stock:write"),data=productSchema.parse(input);const existing=await prisma.product.findFirst({where:{id,tenantId},select:{id:true}});if(!existing)throw new Error("Produit introuvable");if(data.categoryId&&!await prisma.productCategory.findFirst({where:{id:data.categoryId,tenantId,active:true}}))throw new Error("Catégorie introuvable");try{return await prisma.product.update({where:{id},data:productData(data),include:{category:true}})}catch(error){return duplicateProductError(error)}}
export async function setProductActive(id:string,active:boolean,context:CustomerContext){const tenantId=ctx(context,"stock:write"),result=await prisma.product.updateMany({where:{id,tenantId},data:{active}});if(!result.count)throw new Error("Produit introuvable");return prisma.product.findFirstOrThrow({where:{id,tenantId},include:{category:true}})}
export async function moveStock(input:{warehouseId:string;productId:string;quantity:number;type:MovementType;reference?:string},context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:write");if(!Number.isFinite(input.quantity)||input.quantity===0)throw new Error("Quantité invalide");return prisma.$transaction(async tx=>{const warehouse=await tx.warehouse.findFirst({where:{id:input.warehouseId,tenantId}});const product=await tx.product.findFirst({where:{id:input.productId,tenantId}});if(!warehouse||!product)throw new Error("Entrepôt ou produit introuvable");const aggregate=await tx.stockMovement.aggregate({where:{warehouseId:input.warehouseId,productId:input.productId},_sum:{quantity:true}});const balance=Number(aggregate._sum.quantity??0);if(input.quantity<0&&balance+input.quantity<0)throw new Error("Stock insuffisant");return tx.stockMovement.create({data:{...input,quantity:new Prisma.Decimal(input.quantity),createdById:"system"}})})}
export async function stockByWarehouse(context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:read");const movements=await prisma.stockMovement.findMany({where:{warehouse:{tenantId}},include:{warehouse:true}});return movements.reduce<Record<string,number>>((stock,m)=>{const key=`${m.warehouseId}:${m.productId}`;stock[key]=(stock[key]??0)+Number(m.quantity);return stock},{})}
export async function createWarehouse(input:unknown,context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:write"),data=warehouseSchema.parse(input);return prisma.warehouse.create({data:{...data,tenantId}})}
export async function listCategories(context:CustomerContext,active?:boolean){const tenantId=ctx(context,"stock:read");return prisma.productCategory.findMany({where:{tenantId,...(active===undefined?{}:{active})},orderBy:{name:"asc"}})}
export async function createCategory(input:unknown,context:CustomerContext){const tenantId=ctx(context,"stock:write"),data=categorySchema.parse(input);return prisma.productCategory.create({data:{...data,tenantId}})}
export async function updateCategory(id:string,input:unknown,context:CustomerContext){const tenantId=ctx(context,"stock:write"),data=categorySchema.parse(input),result=await prisma.productCategory.updateMany({where:{id,tenantId},data});if(!result.count)throw new Error("Catégorie introuvable");return prisma.productCategory.findFirstOrThrow({where:{id,tenantId}})}
export async function setCategoryActive(id:string,active:boolean,context:CustomerContext){const tenantId=ctx(context,"stock:write");if(!active&&await prisma.product.count({where:{tenantId,categoryId:id}}))throw new Error("Cette catégorie est utilisée par des produits et ne peut pas être archivée");const result=await prisma.productCategory.updateMany({where:{id,tenantId},data:{active}});if(!result.count)throw new Error("Catégorie introuvable");return prisma.productCategory.findFirstOrThrow({where:{id,tenantId}})}
export async function listUnits(context:CustomerContext,active?:boolean){const tenantId=ctx(context,"stock:read");return prisma.unit.findMany({where:{tenantId,...(active===undefined?{}:{active})},orderBy:{name:"asc"}})}
export async function createUnit(input:unknown,context:CustomerContext){const tenantId=ctx(context,"stock:write"),data=unitSchema.parse(input);return prisma.unit.create({data:{...data,tenantId}})}
export async function updateUnit(id:string,input:unknown,context:CustomerContext){const tenantId=ctx(context,"stock:write"),data=unitSchema.parse(input),result=await prisma.unit.updateMany({where:{id,tenantId},data});if(!result.count)throw new Error("Unité introuvable");return prisma.unit.findFirstOrThrow({where:{id,tenantId}})}
export async function setUnitActive(id:string,active:boolean,context:CustomerContext){const tenantId=ctx(context,"stock:write");const unit=await prisma.unit.findFirst({where:{id,tenantId}});if(!unit)throw new Error("Unité introuvable");if(!active&&await prisma.product.count({where:{tenantId,unit:unit.symbol}}))throw new Error("Cette unité est utilisée par des produits et ne peut pas être archivée");return prisma.unit.update({where:{id},data:{active}})}
export async function transferStock(input:{fromWarehouseId:string;toWarehouseId:string;productId:string;quantity:number;reference?:string},context:{tenantId?:string;role:Role}){if(input.fromWarehouseId===input.toWarehouseId)throw new Error("Les entrepôts doivent être différents");const tenantId=ctx(context,"stock:write");if(!Number.isFinite(input.quantity)||input.quantity<=0)throw new Error("Quantité invalide");return prisma.$transaction(async tx=>{const warehouses=await tx.warehouse.findMany({where:{id:{in:[input.fromWarehouseId,input.toWarehouseId]},tenantId}});const product=await tx.product.findFirst({where:{id:input.productId,tenantId}});if(warehouses.length!==2||!product)throw new Error("Transfert introuvable");const total=await tx.stockMovement.aggregate({where:{warehouseId:input.fromWarehouseId,productId:input.productId},_sum:{quantity:true}});if(Number(total._sum.quantity??0)<input.quantity)throw new Error("Stock insuffisant");const reference=input.reference??`TRF-${crypto.randomUUID()}`;await tx.stockMovement.create({data:{warehouseId:input.fromWarehouseId,productId:input.productId,type:MovementType.TRANSFER_OUT,quantity:new Prisma.Decimal(-input.quantity),createdById:"system",reference}});return tx.stockMovement.create({data:{warehouseId:input.toWarehouseId,productId:input.productId,type:MovementType.TRANSFER_IN,quantity:new Prisma.Decimal(input.quantity),createdById:"system",reference}})})}
