import { z } from "zod";
import { MovementType, Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { assertTenant, can, type Role } from "@/lib/tenant";

const customerSchema=z.object({name:z.string().min(2),phone:z.string().min(6).optional(),taxIdentifier:z.string().min(3).optional(),creditLimit:z.coerce.number().min(0).default(0),paymentTermsDays:z.coerce.number().int().min(0).default(0),addresses:z.array(z.object({label:z.string().min(1),address:z.string().min(4),isDefault:z.boolean().default(false)})).default([])});
const productSchema=z.object({sku:z.string().min(2),name:z.string().min(2),unit:z.string().min(1),sellingPrice:z.coerce.number().min(0),purchasePrice:z.coerce.number().min(0).default(0),taxRate:z.coerce.number().min(0).max(100).default(19),minimumStock:z.coerce.number().min(0).default(0),categoryId:z.string().optional()});
const ctx=(context:{tenantId?:string;role:Role},permission:string)=>{if(!can(context.role,permission))throw new Error("Action non autorisée");return assertTenant(context.tenantId)};
const text=z.string().trim().min(1);
const warehouseSchema=z.object({name:text.min(2)});
const categorySchema=z.object({name:text.min(2)});
const unitSchema=z.object({name:text.min(2),symbol:text.max(12)});
const normalized=(value?:string)=>value?.replace(/[^+\d]/g,"")||undefined;
export async function createCustomer(input:unknown,context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"customers:write"),data=customerSchema.parse(input);try{return await prisma.customer.create({data:{...data,tenantId,creditLimit:new Prisma.Decimal(data.creditLimit),addresses:{create:data.addresses}}});}catch{throw new Error("Un client avec ce téléphone ou identifiant fiscal existe déjà")}}
export async function listCustomers(context:{tenantId?:string;role:Role},query="",page=1){const tenantId=ctx(context,"customers:read");return prisma.customer.findMany({where:{tenantId,name:{contains:query,mode:"insensitive"}},include:{addresses:true},take:25,skip:(page-1)*25,orderBy:{name:"asc"}})}
export async function createProduct(input:unknown,context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:write"),data=productSchema.parse(input);return prisma.product.create({data:{...data,tenantId,sellingPrice:new Prisma.Decimal(data.sellingPrice),purchasePrice:new Prisma.Decimal(data.purchasePrice),taxRate:new Prisma.Decimal(data.taxRate),minimumStock:new Prisma.Decimal(data.minimumStock)}})}
export async function moveStock(input:{warehouseId:string;productId:string;quantity:number;type:MovementType;reference?:string},context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:write");if(!Number.isFinite(input.quantity)||input.quantity===0)throw new Error("Quantité invalide");return prisma.$transaction(async tx=>{const warehouse=await tx.warehouse.findFirst({where:{id:input.warehouseId,tenantId}});const product=await tx.product.findFirst({where:{id:input.productId,tenantId}});if(!warehouse||!product)throw new Error("Entrepôt ou produit introuvable");const aggregate=await tx.stockMovement.aggregate({where:{warehouseId:input.warehouseId,productId:input.productId},_sum:{quantity:true}});const balance=Number(aggregate._sum.quantity??0);if(input.quantity<0&&balance+input.quantity<0)throw new Error("Stock insuffisant");return tx.stockMovement.create({data:{...input,quantity:new Prisma.Decimal(input.quantity),createdById:"system"}})})}
export async function stockByWarehouse(context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:read");const movements=await prisma.stockMovement.findMany({where:{warehouse:{tenantId}},include:{warehouse:true}});return movements.reduce<Record<string,number>>((stock,m)=>{const key=`${m.warehouseId}:${m.productId}`;stock[key]=(stock[key]??0)+Number(m.quantity);return stock},{})}
export async function createWarehouse(input:unknown,context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:write"),data=warehouseSchema.parse(input);return prisma.warehouse.create({data:{...data,tenantId}})}
export async function createCategory(input:unknown,context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:write"),data=categorySchema.parse(input);return prisma.productCategory.create({data:{...data,tenantId}})}
export async function createUnit(input:unknown,context:{tenantId?:string;role:Role}){const tenantId=ctx(context,"stock:write"),data=unitSchema.parse(input);return prisma.unit.create({data:{...data,tenantId}})}
export async function transferStock(input:{fromWarehouseId:string;toWarehouseId:string;productId:string;quantity:number;reference?:string},context:{tenantId?:string;role:Role}){if(input.fromWarehouseId===input.toWarehouseId)throw new Error("Les entrepôts doivent être différents");const tenantId=ctx(context,"stock:write");if(!Number.isFinite(input.quantity)||input.quantity<=0)throw new Error("Quantité invalide");return prisma.$transaction(async tx=>{const warehouses=await tx.warehouse.findMany({where:{id:{in:[input.fromWarehouseId,input.toWarehouseId]},tenantId}});const product=await tx.product.findFirst({where:{id:input.productId,tenantId}});if(warehouses.length!==2||!product)throw new Error("Transfert introuvable");const total=await tx.stockMovement.aggregate({where:{warehouseId:input.fromWarehouseId,productId:input.productId},_sum:{quantity:true}});if(Number(total._sum.quantity??0)<input.quantity)throw new Error("Stock insuffisant");const reference=input.reference??`TRF-${crypto.randomUUID()}`;await tx.stockMovement.create({data:{warehouseId:input.fromWarehouseId,productId:input.productId,type:MovementType.TRANSFER_OUT,quantity:new Prisma.Decimal(-input.quantity),createdById:"system",reference}});return tx.stockMovement.create({data:{warehouseId:input.toWarehouseId,productId:input.productId,type:MovementType.TRANSFER_IN,quantity:new Prisma.Decimal(input.quantity),createdById:"system",reference}})})}
