import { MovementType, Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { assertTenant, can, type Role } from "@/lib/tenant";

type Context={tenantId?:string;role:Role;userId?:string};
const context=(value:Context,permission:string)=>{if(!can(value.role,permission))throw new Error("Action non autorisée");return assertTenant(value.tenantId)};
const warehouseSchema=z.object({code:z.string().trim().min(2).max(20),name:z.string().trim().min(2).max(120),address:z.string().trim().max(400).optional(),city:z.string().trim().max(80).optional(),contactName:z.string().trim().max(120).optional(),contactPhone:z.string().trim().max(40).optional()});
const quantity=z.coerce.number().finite().positive();
const movementSchema=z.object({warehouseId:z.string().min(1),productId:z.string().min(1),quantity,reference:z.string().trim().max(100).optional(),notes:z.string().trim().max(1000).optional(),idempotencyKey:z.string().trim().min(12).max(120)});
const transferSchema=movementSchema.extend({destinationWarehouseId:z.string().min(1)});
const adjustmentSchema=movementSchema.extend({quantity:z.coerce.number().finite().refine(value=>value!==0,"La quantité ne peut pas être nulle"),notes:z.string().trim().min(3,"Le motif est obligatoire").max(1000)});
const decimal=(value:number)=>new Prisma.Decimal(value);
async function audit(tx:Prisma.TransactionClient,tenantId:string,actorId:string|undefined,action:string,entity:string,entityId:string,metadata?:Prisma.InputJsonValue){await tx.auditEvent.create({data:{tenantId,actorId:actorId??"system",action,entity,entityId,metadata}})}
export async function listWarehouses(ctx:Context,query="",active?:boolean){const tenantId=context(ctx,"stock:read");return prisma.warehouse.findMany({where:{tenantId,...(active===undefined?{}:{active}),...(query?{OR:[{name:{contains:query,mode:"insensitive"}},{code:{contains:query,mode:"insensitive"}},{city:{contains:query,mode:"insensitive"}}]}:{})},orderBy:{name:"asc"}})}
export async function createWarehouse(input:unknown,ctx:Context){const tenantId=context(ctx,"stock:write"),data=warehouseSchema.parse(input);try{return await prisma.warehouse.create({data:{...data,code:data.code.toUpperCase(),tenantId}})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")throw new Error("Ce code d’entrepôt existe déjà");throw error}}
export async function updateWarehouse(id:string,input:unknown,ctx:Context){const tenantId=context(ctx,"stock:write"),data=warehouseSchema.parse(input),result=await prisma.warehouse.updateMany({where:{id,tenantId},data:{...data,code:data.code.toUpperCase()}});if(!result.count)throw new Error("Entrepôt introuvable");return prisma.warehouse.findFirstOrThrow({where:{id,tenantId}})}
export async function setWarehouseActive(id:string,active:boolean,ctx:Context){const tenantId=context(ctx,"stock:write");if(!active&&await prisma.stockLevel.count({where:{warehouse:{id,tenantId},quantity:{not:new Prisma.Decimal(0)}}}))throw new Error("Cet entrepôt contient du stock et ne peut pas être archivé");const result=await prisma.warehouse.updateMany({where:{id,tenantId},data:{active}});if(!result.count)throw new Error("Entrepôt introuvable");return prisma.warehouse.findFirstOrThrow({where:{id,tenantId}})}
export async function getWarehouse(id:string,ctx:Context){const tenantId=context(ctx,"stock:read"),warehouse=await prisma.warehouse.findFirst({where:{id,tenantId}});if(!warehouse)throw new Error("Entrepôt introuvable");return warehouse}
async function apply(tx:Prisma.TransactionClient,tenantId:string,ctx:Context,input:z.infer<typeof movementSchema>,type:MovementType,sign:1|-1){const existing=await tx.stockMovement.findFirst({where:{warehouseId:input.warehouseId,idempotencyKey:input.idempotencyKey}});if(existing)return existing;const [warehouse,product]=await Promise.all([tx.warehouse.findFirst({where:{id:input.warehouseId,tenantId,active:true}}),tx.product.findFirst({where:{id:input.productId,tenantId,active:true}})]);if(!warehouse||!product)throw new Error("Produit ou entrepôt introuvable ou archivé");const change=decimal(input.quantity*sign);const level=await tx.stockLevel.upsert({where:{productId_warehouseId:{productId:input.productId,warehouseId:input.warehouseId}},create:{productId:input.productId,warehouseId:input.warehouseId,quantity:new Prisma.Decimal(0)},update:{}});const reserved=await tx.orderReservation.aggregate({where:{tenantId,warehouseId:input.warehouseId,productId:input.productId,releasedAt:null},_sum:{quantity:true,consumedQuantity:true}});const reservedQuantity=new Prisma.Decimal(reserved._sum.quantity??0).minus(reserved._sum.consumedQuantity??0);if(level.quantity.add(change).isNegative()||change.isNegative()&&level.quantity.minus(reservedQuantity).add(change).isNegative())throw new Error("Stock insuffisant ou réservé");await tx.stockLevel.update({where:{id:level.id},data:{quantity:{increment:change}}});const movement=await tx.stockMovement.create({data:{warehouseId:input.warehouseId,productId:input.productId,type,quantity:change,createdById:ctx.userId??"system",reference:input.reference,notes:input.notes,idempotencyKey:input.idempotencyKey}});await audit(tx,tenantId,ctx.userId,"stock."+type,"StockMovement",movement.id,{quantity:input.quantity});return movement}
export async function receiveStock(input:unknown,ctx:Context){const tenantId=context(ctx,"stock:write"),data=movementSchema.parse(input);return prisma.$transaction(tx=>apply(tx,tenantId,ctx,data,MovementType.PURCHASE_RECEIPT,1),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function removeStock(input:unknown,ctx:Context){const tenantId=context(ctx,"stock:write"),data=movementSchema.parse(input);return prisma.$transaction(tx=>apply(tx,tenantId,ctx,data,MovementType.ADJUSTMENT,-1),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function adjustStock(input:unknown,ctx:Context){const tenantId=context(ctx,"stock:write"),data=adjustmentSchema.parse(input);return prisma.$transaction(tx=>apply(tx,tenantId,ctx,{...data,quantity:Math.abs(data.quantity)},MovementType.ADJUSTMENT,data.quantity>0?1:-1),{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function transferStockSafe(input:unknown,ctx:Context){const tenantId=context(ctx,"stock:write"),data=transferSchema.parse(input);if(data.warehouseId===data.destinationWarehouseId)throw new Error("Les entrepôts doivent être différents");return prisma.$transaction(async tx=>{const existing=await tx.stockMovement.findFirst({where:{warehouseId:data.warehouseId,idempotencyKey:data.idempotencyKey}});if(existing)return existing;const transferId=crypto.randomUUID();await apply(tx,tenantId,ctx,data,MovementType.TRANSFER_OUT,-1);return apply(tx,tenantId,ctx,{...data,warehouseId:data.destinationWarehouseId,idempotencyKey:`${data.idempotencyKey}:in`},MovementType.TRANSFER_IN,1)},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function stockOverview(ctx:Context){const tenantId=context(ctx,"stock:read");return prisma.stockLevel.findMany({where:{warehouse:{tenantId},product:{tenantId}},include:{warehouse:true,product:true},orderBy:{product:{name:"asc"}}})}
export async function listMovements(ctx:Context,options:{productId?:string;warehouseId?:string;query?:string;page?:number}={}){const tenantId=context(ctx,"stock:read"),page=Math.max(1,options.page??1),query=options.query?.trim()??"";const where={warehouse:{tenantId},...(options.productId?{productId:options.productId}:{}),...(options.warehouseId?{warehouseId:options.warehouseId}:{}),...(query?{OR:[{reference:{contains:query,mode:"insensitive" as const}},{notes:{contains:query,mode:"insensitive" as const}},{product:{name:{contains:query,mode:"insensitive" as const}}}]}:{})};const [items,total]=await prisma.$transaction([prisma.stockMovement.findMany({where,include:{warehouse:true,product:true},orderBy:{createdAt:"desc"},take:25,skip:(page-1)*25}),prisma.stockMovement.count({where})]);return{items,pagination:{page,total,totalPages:Math.max(1,Math.ceil(total/25))}}}
export async function lowStock(ctx:Context){const levels=await stockOverview(ctx);return levels.filter(level=>level.quantity.lte(level.product.minimumStock))}
