import { randomUUID } from "node:crypto";
import { ConversationType, MembershipStatus, NotificationType, Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { assertTenant, type Role } from "@/lib/tenant";
import { createNotification } from "@/lib/services/notifications";
import { objectStorage } from "@/lib/storage";

type Context = { tenantId?: string; userId: string; role: Role };
const bodySchema = z.object({ body: z.string().trim().min(1).max(5000), clientId: z.string().trim().min(8).max(120) });
const allowedFiles = new Map([["image/png", "png"], ["image/jpeg", "jpg"], ["image/webp", "webp"], ["application/pdf", "pdf"], ["text/plain", "txt"], ["text/csv", "csv"]]);
function tenant(context: Context) { return assertTenant(context.tenantId); }
async function membership(tenantId: string, userId: string) { const record = await prisma.membership.findUnique({ where: { tenantId_userId: { tenantId, userId } } }); if (!record || record.status !== MembershipStatus.ACTIVE) throw new Error("Accès employé indisponible"); return record; }
async function conversationFor(id: string, context: Context) { const tenantId = tenant(context); await membership(tenantId, context.userId); const conversation = await prisma.conversation.findFirst({ where: { id, tenantId, participants: { some: { userId: context.userId } } }, include: { participants: { include: { user: { select: { id: true, name: true, email: true } } } } } }); if (!conversation) throw new Error("Conversation introuvable"); return conversation; }
export async function listConversations(context: Context) { const tenantId = tenant(context); await membership(tenantId, context.userId); const conversations = await prisma.conversation.findMany({ where: { tenantId, participants: { some: { userId: context.userId } } }, include: { participants: { include: { user: { select: { id: true, name: true, email: true } } } }, messages: { orderBy: { createdAt: "desc" }, take: 1, include: { sender: { select: { name: true } }, attachments: { select: { id: true, fileName: true, mimeType: true, size: true } } } } }, orderBy: { updatedAt: "desc" } }); const unread = await Promise.all(conversations.map(async (conversation) => ({ id: conversation.id, count: await prisma.message.count({ where: { conversationId: conversation.id, senderId: { not: context.userId }, readStates: { none: { userId: context.userId } } } }) }))); return conversations.map((conversation) => ({ ...conversation, unreadCount: unread.find((item) => item.id === conversation.id)?.count ?? 0 })); }
export async function listPeople(context: Context) { const tenantId = tenant(context); await membership(tenantId, context.userId); return prisma.membership.findMany({ where: { tenantId, status: MembershipStatus.ACTIVE, userId: { not: context.userId } }, select: { userId: true, role: true, user: { select: { name: true, email: true } } }, orderBy: { user: { name: "asc" } } }); }
export async function createConversation(input: unknown, context: Context) { const tenantId = tenant(context); await membership(tenantId, context.userId); const data = z.object({ type: z.nativeEnum(ConversationType).default(ConversationType.DIRECT), title: z.string().trim().max(120).optional(), participantIds: z.array(z.string()).min(1).max(100) }).parse(input); const ids = [...new Set([context.userId, ...data.participantIds])]; const active = await prisma.membership.findMany({ where: { tenantId, userId: { in: ids }, status: MembershipStatus.ACTIVE }, select: { userId: true } }); if (active.length !== ids.length) throw new Error("Chaque participant doit appartenir à l’entreprise et être actif"); return prisma.conversation.create({ data: { tenantId, type: data.type, title: data.title, createdById: context.userId, participants: { create: ids.map((userId) => ({ userId })) } }, include: { participants: { include: { user: { select: { id: true, name: true, email: true } } } } } }); }
export async function getConversation(id: string, context: Context) { return conversationFor(id, context); }
export async function listMessages(id: string, context: Context) { const conversation = await conversationFor(id, context); return prisma.message.findMany({ where: { conversationId: conversation.id }, include: { sender: { select: { id: true, name: true } }, attachments: { select: { id: true, fileName: true, mimeType: true, size: true } } }, orderBy: { createdAt: "asc" }, take: 300 }); }
function attachmentKind(buffer: Buffer, mimeType: string) { const extension = allowedFiles.get(mimeType); if (!extension) return null; if (mimeType === "application/pdf" && buffer.subarray(0, 5).toString() !== "%PDF-") return null; if (mimeType === "image/png" && !buffer.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) return null; if (mimeType === "image/jpeg" && !buffer.subarray(0, 3).equals(Buffer.from([255, 216, 255]))) return null; if (mimeType === "image/webp" && !(buffer.toString("ascii", 0, 4) === "RIFF" && buffer.toString("ascii", 8, 12) === "WEBP")) return null; return extension; }
export async function sendMessage(id: string, input: { body: string; clientId: string; file?: { buffer: Buffer; fileName: string; mimeType: string } }, context: Context) { const conversation = await conversationFor(id, context); const data = bodySchema.parse({ body: input.body, clientId: input.clientId }); if (input.file && (input.file.buffer.length === 0 || input.file.buffer.length > 10 * 1024 * 1024 || !attachmentKind(input.file.buffer, input.file.mimeType))) throw new Error("Pièce jointe refusée : format ou taille invalide"); const existing = await prisma.message.findUnique({ where: { conversationId_clientId: { conversationId: id, clientId: data.clientId } }, include: { attachments: true } }); if (existing) return existing; let storedKey: string | undefined; if (input.file) { const extension = attachmentKind(input.file.buffer, input.file.mimeType)!; storedKey = `messages/${conversation.tenantId}/${randomUUID()}.${extension}`; await objectStorage().put(storedKey, input.file.buffer, input.file.mimeType); }
  try { const message = await prisma.$transaction(async (tx) => { const created = await tx.message.create({ data: { conversationId: id, senderId: context.userId, body: data.body, clientId: data.clientId, attachments: input.file && storedKey ? { create: { tenantId: conversation.tenantId, objectKey: storedKey, fileName: input.file.fileName.slice(0, 180), mimeType: input.file.mimeType, size: input.file.buffer.length } } : undefined }, include: { sender: { select: { id: true, name: true } }, attachments: true } }); await tx.conversation.update({ where: { id }, data: { updatedAt: new Date() } }); return created; }); const recipients = conversation.participants.filter((participant) => participant.userId !== context.userId); await Promise.all(recipients.map((recipient) => createNotification({ tenantId: conversation.tenantId, recipientId: recipient.userId, type: input.file ? NotificationType.EMPLOYEE_ATTACHMENT : NotificationType.EMPLOYEE_MESSAGE, title: input.file ? "Nouvelle pièce jointe" : "Nouveau message", body: `${conversation.participants.find((participant) => participant.userId === context.userId)?.user.name ?? "Un collègue"} vous a écrit.`, href: `/messages/${conversation.id}`, dedupeKey: `message:${message.id}:${recipient.userId}`, metadata: { conversationId: conversation.id, messageId: message.id } }).catch(() => undefined))); return message; } catch (error) { if (storedKey) await objectStorage().delete(storedKey).catch(() => undefined); if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return prisma.message.findUniqueOrThrow({ where: { conversationId_clientId: { conversationId: id, clientId: data.clientId } }, include: { attachments: true } }); throw error; }
}
export async function markConversationRead(id: string, context: Context) { const messages = await listMessages(id, context); await Promise.all(messages.map((message) => prisma.messageReadState.upsert({ where: { messageId_userId: { messageId: message.id, userId: context.userId } }, create: { messageId: message.id, userId: context.userId }, update: { readAt: new Date() } }))); return { read: messages.length }; }
export async function readAttachment(id: string, context: Context) { const tenantId = tenant(context); const attachment = await prisma.messageAttachment.findFirst({ where: { id, tenantId, message: { conversation: { participants: { some: { userId: context.userId } } } } } }); if (!attachment) throw new Error("Pièce jointe introuvable"); const object = await objectStorage().get(attachment.objectKey); if (!object) throw new Error("Pièce jointe indisponible"); return { ...object, fileName: attachment.fileName, mimeType: attachment.mimeType }; }
